"""Regenerate a structural ERD from the implemented PostgreSQL schema.

We do not depend on graphviz/eralchemy in the default validation path because
those packages are hard to install on Windows. Instead we emit a deterministic
Mermaid ER diagram from ``information_schema`` so the output can be diffed
against ``docs/database/ERD.md`` line by line.

Usage:
    python scripts/regenerate_erd.py [output.md]

The script writes a Mermaid ``erDiagram`` block listing every base table plus
its foreign-key relationships, ordered alphabetically for stable diffs. The
default output path is ``.validation/erd_generated.md`` (git-ignored and
matching the CI gate's output location); pass an explicit path as ``argv[1]``
to override.
"""

from __future__ import annotations

import sys
from pathlib import Path

import sqlalchemy as sa

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _load_env

DATABASE_URL = _load_env.load()

_PARTITION_PREFIXES = ("usage_records_y", "analytics_events_y", "event_log_y", "audit_log_y")
_PARTITION_DEFAULTS = {
    "usage_records_default",
    "analytics_events_default",
    "event_log_default",
    "audit_log_default",
}


def _is_partition_child(table_name: str) -> bool:
    return table_name in _PARTITION_DEFAULTS or table_name.startswith(_PARTITION_PREFIXES)


def main(argv: list[str]) -> int:
    out_path = Path(argv[1]) if len(argv) > 1 else Path(".validation") / "erd_generated.md"
    engine = sa.create_engine(DATABASE_URL, future=True)
    # Use pg_catalog directly — information_schema joins over constraint_column_usage
    # are very slow on Supabase (statement_timeout = 2 min) once partition children
    # multiply the constraint count. We also pre-filter inheritance children so we
    # only emit relationships between logical base tables.
    with engine.connect() as conn:
        tables = sorted(
            r[0]
            for r in conn.execute(
                sa.text(
                    """
                    SELECT c.relname
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE n.nspname = 'public'
                      AND c.relkind IN ('r', 'p')        -- ordinary + partitioned parent
                      AND NOT EXISTS (                    -- exclude partition children
                          SELECT 1 FROM pg_inherits i
                          WHERE i.inhrelid = c.oid
                      )
                    """
                )
            ).all()
            if not r[0].startswith("_") and r[0] != "alembic_version"
        )
        fks = conn.execute(
            sa.text(
                """
                SELECT
                    src.relname  AS src,
                    src_col.attname AS src_col,
                    dst.relname  AS dst,
                    dst_col.attname AS dst_col,
                    CASE con.confdeltype
                        WHEN 'a' THEN 'NO ACTION'
                        WHEN 'r' THEN 'RESTRICT'
                        WHEN 'c' THEN 'CASCADE'
                        WHEN 'n' THEN 'SET NULL'
                        WHEN 'd' THEN 'SET DEFAULT'
                    END AS on_delete
                FROM pg_constraint con
                JOIN pg_class src ON src.oid = con.conrelid
                JOIN pg_namespace srcns ON srcns.oid = src.relnamespace
                JOIN pg_class dst ON dst.oid = con.confrelid
                JOIN pg_attribute src_col
                  ON src_col.attrelid = con.conrelid
                 AND src_col.attnum = con.conkey[1]
                JOIN pg_attribute dst_col
                  ON dst_col.attrelid = con.confrelid
                 AND dst_col.attnum = con.confkey[1]
                WHERE con.contype = 'f'
                  AND srcns.nspname = 'public'
                  AND NOT EXISTS (
                      SELECT 1 FROM pg_inherits i WHERE i.inhrelid = src.oid
                  )
                ORDER BY src.relname, src_col.attname
                """
            )
        ).all()

    lines: list[str] = [
        "# Generated ERD (from implemented schema)",
        "",
        "_Auto-generated by `scripts/regenerate_erd.py` — diff against `docs/database/ERD.md`._",
        "",
        "```mermaid",
        "erDiagram",
    ]
    for t in tables:
        lines.append(f"  {t} {{ }}")
    seen: set[tuple[str, str, str, str]] = set()
    for src, src_col, dst, dst_col, _on_delete in fks:
        if _is_partition_child(src) or _is_partition_child(dst):
            continue
        if src.startswith("_") or dst.startswith("_"):
            continue
        key = (src, src_col, dst, dst_col)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"  {dst} ||--o{{ {src} : {src_col}")
    lines.append("```")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path.resolve()} ({len(tables)} tables, {len(seen)} FKs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
